version: '3.9'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  googlereviews:
    container_name: googlereviews
    build:
      context: .
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgresdb
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - googlereviews
      - redis
         
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celerybeat
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - googlereviews
      - redis

  redis:
    image: "redis:alpine"


volumes:
  postgres-data: