version: '3.9'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  googlereviews:
    container_name: googlereviews
    build:
      context: .
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgresdb

volumes:
  postgres-data: